In [1]:
import pandas as pd
import numpy as np

dataframe1 = pd.read_json('iris.json')

In [2]:
dataframe1

     sepalLength  sepalWidth  petalLength  petalWidth    species
0            5.1         3.5          1.4         0.2     setosa
1            4.9         3.0          1.4         0.2     setosa
2            4.7         3.2          1.3         0.2     setosa
3            4.6         3.1          1.5         0.2     setosa
4            5.0         3.6          1.4         0.2     setosa
..           ...         ...          ...         ...        ...
145          6.7         3.0          5.2         2.3  virginica
146          6.3         2.5          5.0         1.9  virginica
147          6.5         3.0          5.2         2.0  virginica
148          6.2         3.4          5.4         2.3  virginica
149          5.9         3.0          5.1         1.8  virginica

[150 rows x 5 columns]

In [5]:
dataframe1.head()
print(dataframe1)

     sepalLength  sepalWidth  petalLength  petalWidth    species
0            5.1         3.5          1.4         0.2     setosa
1            4.9         3.0          1.4         0.2     setosa
2            4.7         3.2          1.3         0.2     setosa
3            4.6         3.1          1.5         0.2     setosa
4            5.0         3.6          1.4         0.2     setosa
..           ...         ...          ...         ...        ...
145          6.7         3.0          5.2         2.3  virginica
146          6.3         2.5          5.0         1.9  virginica
147          6.5         3.0          5.2         2.0  virginica
148          6.2         3.4          5.4         2.3  virginica
149          5.9         3.0          5.1         1.8  virginica

[150 rows x 5 columns]

In [6]:
print(dataframe1[96:])

     sepalLength  sepalWidth  petalLength  petalWidth     species
96           5.7         2.9          4.2         1.3  versicolor
97           6.2         2.9          4.3         1.3  versicolor
98           5.1         2.5          3.0         1.1  versicolor
99           5.7         2.8          4.1         1.3  versicolor
100          6.3         3.3          6.0         2.5   virginica
101          5.8         2.7          5.1         1.9   virginica
102          7.1         3.0          5.9         2.1   virginica
103          6.3         2.9          5.6         1.8   virginica
104          6.5         3.0          5.8         2.2   virginica
105          7.6         3.0          6.6         2.1   virginica
106          4.9         2.5          4.5         1.7   virginica
107          7.3         2.9          6.3         1.8   virginica
108          6.7         2.5          5.8         1.8   virginica
109          7.2         3.6          6.1         2.5   virginica
110          6.5         3.2          5.1         2.0   virginica
111          6.4         2.7          5.3         1.9   virginica
112          6.8         3.0          5.5         2.1   virginica
113          5.7         2.5          5.0         2.0   virginica
114          5.8         2.8          5.1         2.4   virginica
115          6.4         3.2          5.3         2.3   virginica
116          6.5         3.0          5.5         1.8   virginica
117          7.7         3.8          6.7         2.2   virginica
118          7.7         2.6          6.9         2.3   virginica
119          6.0         2.2          5.0         1.5   virginica
120          6.9         3.2          5.7         2.3   virginica
121          5.6         2.8          4.9         2.0   virginica
122          7.7         2.8          6.7         2.0   virginica
123          6.3         2.7          4.9         1.8   virginica
124          6.7         3.3          5.7         2.1   virginica
125          7.2         3.2          6.0         1.8   virginica
126          6.2         2.8          4.8         1.8   virginica
127          6.1         3.0          4.9         1.8   virginica
128          6.4         2.8          5.6         2.1   virginica
129          7.2         3.0          5.8         1.6   virginica
130          7.4         2.8          6.1         1.9   virginica
131          7.9         3.8          6.4         2.0   virginica
132          6.4         2.8          5.6         2.2   virginica
133          6.3         2.8          5.1         1.5   virginica
134          6.1         2.6          5.6         1.4   virginica
135          7.7         3.0          6.1         2.3   virginica
136          6.3         3.4          5.6         2.4   virginica
137          6.4         3.1          5.5         1.8   virginica
138          6.0         3.0          4.8         1.8   virginica
139          6.9         3.1          5.4         2.1   virginica
140          6.7         3.1          5.6         2.4   virginica
141          6.9         3.1          5.1         2.3   virginica
142          5.8         2.7          5.1         1.9   virginica
143          6.8         3.2          5.9         2.3   virginica
144          6.7         3.3          5.7         2.5   virginica
145          6.7         3.0          5.2         2.3   virginica
146          6.3         2.5          5.0         1.9   virginica
147          6.5         3.0          5.2         2.0   virginica
148          6.2         3.4          5.4         2.3   virginica
149          5.9         3.0          5.1         1.8   virginica

In [7]:
#writing the json

popularity = {"character":["spiderman", "spiderman","superman", "superman", "ironman","ironman","jerry","jerry", "tom", "tom"],
             "popularity":["first","second","third","fourth","fifth","first","second","third","fourth","fifth"],
             "score1":[60,57,46,59,47,60,57,46,59,47],
             "score2":[60,57,46,59,47,60,57,46,59,47]}

dataframe2 = pd.DataFrame(popularity)
dataframe2.to_json('popularity.json')